# Generated by Django 5.1.6 on 2025-02-21 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_alter_lesson_video_link"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateTimeField(auto_now_add=True, verbose_name="Payment date")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Amount")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Bank Transfer", "Bank Transfer")],
                        max_length=20,
                        verbose_name="Payment method",
                    ),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="education.course",
                        verbose_name="Paid course",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="education.lesson",
                        verbose_name="Paid lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Payment",
                    ),
                ),
            ],
        ),
    ]
