# Generated by Django 5.1.6 on 2025-02-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Transfer", "Transfer")], max_length=20, verbose_name="Payment method"
            ),
        ),
    ]
