services:
  backend:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    expose:
      - "6379"
    env_file:
      - ./.env
    volumes:
      - .:/cache

  celery:
    command: celery -A config worker -l INFO
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - backend

  celery-beat:
    command: celery -A config beat -l INFO
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - backend

volumes:
  postgres_data:
  static_volume:

networks:
  default: