# Generated by Django 5.1.6 on 2025-02-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                (
                    "preview",
                    models.ImageField(
                        default="courses/default_course.png", upload_to="courses/", verbose_name="Preview"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "preview",
                    models.ImageField(
                        default="lessons/default_lesson.png", upload_to="lessons/", verbose_name="Preview"
                    ),
                ),
                ("video_link", models.URLField(verbose_name="Video link")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "ordering": ["title"],
            },
        ),
    ]
