# Generated by Django 5.1.6 on 2025-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(blank=True, null=True, verbose_name="Video link"),
        ),
    ]
