# Generated by Django 5.1.6 on 2025-03-04 10:17

import education.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                blank=True, null=True, validators=[education.validators.validate_video_link], verbose_name="Video link"
            ),
        ),
    ]
